### ISSUE TITLE
Reading from nio:/data/user/0/com.app.android/files/nitrite.db failed; file length -1 read length 8192 at 20480 [1.4.196/1]

### ISSUE THREAD

**Issue by ArthurSav** [dizitart/nitrite-database#118]
More of the stacktrace:
```
java.lang.IllegalStateException: Reading from nio:/data/user/0/com.app.android/files/nitrite.db failed; file length -1 read length 8192 at 20480 [1.4.196/1]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
        at org.h2.mvstore.DataUtils.readFully(DataUtils.java:435)
        at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
        at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1704)
        at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1654)
        at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1624)
        at org.dizitart.no2.store.NitriteMVStore.compact(NitriteMVStore.java:64)
        at org.dizitart.no2.Nitrite.compact(Nitrite.java:207)
        at org.dizitart.no2.Nitrite.close(Nitrite.java:251)
```

As with most issues from nitrite, i can't reliably reproduce the crash. Happens at random times and in this instance it happened when trying to close the db.
Android 8.0, nitrite **v3.0.1-SNAPSHOT**

**Comment by ArthurSav** [comment]
Upgraded to nitrite `3.1.0`, still an issue. Happens primarily on async tasks.
I'm using a Singleton and i close the database properly.

Some more stacktraces:

```java
Caused by java.lang.IllegalStateException: Reading from nio:/data/user/0/io.app.android/files/app.db failed; file length -1 read length 8192 at 0 [1.4.197/1]
       at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
       at org.h2.mvstore.DataUtils.readFully(DataUtils.java:417)
       at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
       at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:563)
       at org.h2.mvstore.MVStore.(MVStore.java:361)
       at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
       at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:457)
       at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:359)
       at io.app.android.data.storage.NitriteManager.getNitrite(NitriteManager.java:71)
       at io.app.android.data.storage.NitriteManager.save(NitriteManager.java:145)
       at io.app.android.data.storage.NitriteManager.save(NitriteManager.java:176)
       at io.app.android.data.storage.Database.save(Database.java:49)
       at io.app.android.data.async.UserSync.fetch(UserSync.java:78)
       at io.app.android.data.async.UserSync.doInBackground(UserSync.java:36)
       at io.app.android.data.async.UserSync.doInBackground(UserSync.java:17)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

```java
Caused by java.nio.channels.ClosedByInterruptException
       at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:113)
       at java.nio.FileChannelImpl.readImpl(FileChannelImpl.java:324)
       at java.nio.FileChannelImpl.read(FileChannelImpl.java:287)
       at org.h2.store.fs.FileNio.read(FilePathNio.java:74)
       at org.h2.mvstore.DataUtils.readFully(DataUtils.java:403)
       at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
       at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:563)
       at org.h2.mvstore.MVStore.(MVStore.java:361)
       at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
       at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:457)
       at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:359)
       at io.app.android.data.storage.NitriteManager.getNitrite(NitriteManager.java:71)
       at io.app.android.data.storage.NitriteManager.save(NitriteManager.java:145)
       at io.app.android.data.storage.NitriteManager.save(NitriteManager.java:176)
       at io.app.android.data.storage.Database.save(Database.java:49)
       at io.app.android.data.async.UserSync.fetch(UserSync.java:78)
       at io.app.android.data.async.UserSync.doInBackground(UserSync.java:36)
       at io.app.android.data.async.UserSync.doInBackground(UserSync.java:17)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by anidotnet** [comment]
This was actually an issue with mvstore. See this issue https://github.com/h2database/h2database/issues/227 for reference. 

If possible can you try with 3.2.0 snapshots of nitrite? I have upgraded the mvstore to recent version where they have made the storage engine multi-threaded by default. They also have implemented low-level lock in the store for better synchronization.

**Comment by ArthurSav** [comment]
Can you think of a way to reliably reproduce the issue? I have tried to replicate it with Async task but i not success so far.

**Comment by ArthurSav** [comment]
Took the whole day to investigate

Seems that **h2database** has always been like this. As discussed in h2database/h2database#227, the issue occurs when a thread is interrupted.

Based on a [thread](http://h2-database.66688.n3.nabble.com/ClosedChannelException-on-Thread-Interrupt-td4026421.html) dating back in 2013, i tried to replicate the issue in a nitrite test.

(Modified from [NitriteTest](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/NitriteTest.java))
```
public class NitriteCorruptedTest {
    private Nitrite db;
    private NitriteCollection collection;
    private String fileName = getRandomTempDbFile();
    private Thread thread;

    @Before
    public void setUp() throws ParseException {
        db = new NitriteBuilder()
                .filePath(fileName)
                .compressed()
                .openOrCreate();

        collection = db.getCollection("test");
        collection.remove(ALL);

        thread = new Thread(new Runnable() {
            public void run() {
                for (int i = 0; i < 50000; i++) {
                    Document doc1 = createDocument(String.valueOf(System.currentTimeMillis()), "fn1")
                        .put("lastName", "ln1")
                        .put("data", new byte[]{1, 2, 3})
                        .put("body", "a quick brown fox jump over the lazy dog");
                    collection.insert(doc1);
                }
            }
        });
    }

    @After
    public void tearDown() throws IOException {
        if (!collection.isClosed()) {
            collection.remove(ALL);
            collection.close();
        }
        db.close();
        Files.delete(Paths.get(fileName));
    }

    @Test(timeout = 10000)
    public void testThread() throws InterruptedException {
        thread.start();
        Thread.sleep(1);
        thread.interrupt();
        Thread.sleep(500);
    }
}
```

I still can't reliably reproduce it in an app environment but i'm sure at some point the thread nitrite is running on gets interrupted. 

Also, i found a nitrite method called [shutdownAndWaitTermination()](https://github.com/dizitart/nitrite-database/blob/a1b5c38ef70573bbae88667258ef9e8229c7a0c7/nitrite/src/main/java/org/dizitart/no2/util/ExecutorUtils.java#L85) that uses **Thread.currentThread().interrupt();**. Could this be the cause?

Typical shutdown scenario for me is:
```
@Override protected void onStop() {
    super.onStop();
    closeAllAsyncTasks();
    closeDatabase();
  }
```
Maybe there's room here for an improper shutdown.

But again, h2database is pretty bad at dealing with threads.

Tested with `h2Version=1.4.197`, `h2Version=1.4.198` and `nitriteVersion=3.2.0-SNAPSHOT`

**Comment by anidotnet** [comment]
Thanks a lot for the investigation. I'll try to see if I can fix this.

**Comment by anidotnet** [comment]
The solution I have come up with so far is to execute all mvstore operations in a separate thread pool, thus isolating app threads and db threads. So if app thread gets interrupted, it will not shutdown db operations and render it corrupted.

Something on the line:

```java
Future<Value> value = executor.submit(() -> mvMap.putIfAbsent(nitriteId, document));
try {
    return value.get();
} catch (InterruptedException e) {
    // ignore or rethrow?
} catch (ExecutionException e) {
    // rethrow
}
```
Only one thing I am not sure, should I rethrow the `InterruptedException` or mute. Any thought?

**Comment by ArthurSav** [comment]
Running on a different thread might solve the issue but i think we're avoiding the problem. If the app thread get interrupted then `onStop()` is called which should close the database.

What happens with `nitrite.close()`? My assumption is that i try to close the db, the app thread gets killed before the db finishes closing which in turn causes the exception.

From experimentation, i found out that `nitrite.isClosed()` returns `False` even when `nitrite.close()` has been called. To replicate:

```java

//note - nitrite has already been created in the app thread
Thread thread = new Thread(new Runnable() {
    public void run() {
      for (int i = 0; i < 50000; i++) {
        if (!db.isClosed()) addItemIntoDB();
      }
    }
  });

public void onBtnPressed(){
    thread.start();
  }

@Override protected void onStop() {
    super.onStop();
    thread.interrupt();
    db.close();
  }

```


If `onStop()` gets called while the thread is running then you get this exception:

```java
java.lang.IllegalStateException: This store is closed [1.4.198/4]
```

This should not happen since there's a check in place `if (!db.isClosed()) addItemIntoDB();`

My take from this:
- Can we introduce a new method called `nitrite.isClosing()` which returns `True` when `nitrite.close()` has been called and `False` when it's done.
- Maybe perform onClose operations in another thread pool like you initially suggested.

**Comment by anidotnet** [comment]
First of all, 'isClosed()` and `close()` is not synchronized, one you synchronize it, you won't be able to see the exception. You need to be careful about that.

Secondly. if the app thread closes, we have a jvm shutdown hook in place, which will take care of the closing the database properly, discarding unsaved changes.

Last of all, not only insert, all db operations (read, write, close) will be on separate thread pool, almost like you are accessing a nitrite server from your app, though it is embedded.

But the question still remains, how to handle `InterruptedException` in the calling thread? Should we rethrow and let the app handle it, or just mute it by logging the exception.

**Comment by ArthurSav** [comment]
Personally i don't mind just having warnings in the logs.

**Comment by anidotnet** [comment]
Nah!. Running every mvstore operations from a separate threadpool incurs a lot of performance hit due to context switching overhead.

While running this JMH suite - https://github.com/dizitart/nitrite-database/blob/feature-spatial/nitrite/src/test/java/org/dizitart/no2/jmh/Issue133.java

Result prior to the change (running all mvstore operations on app thread):

Results (numbers are _**microseconds per operation (us/op)**_ ):

| Number of entities | Also read data? | Indexed field disperssion | Iterations | Results |
|--------------------|-----------------|---------------------------|------------|---------|
| 100000             | true            | 5000                      | 12         | 34.769  |
| 100000             | true            | 10000                     | 12         | 20.019  |
| 100000             | true            | 20000                     | 12         | 12.641  |
| 100000             | false           | 5000                      | 12         | 2.998   |
| 100000             | false           | 10000                     | 12         | 2.922   |
| 100000             | false           | 20000                     | 12         | 2.934   |
| 200000             | true            | 5000                      | 12         | 74.123  |
| 200000             | true            | 10000                     | 12         | 39.902  |
| 200000             | true            | 20000                     | 12         | 23.192  |
| 200000             | false           | 5000                      | 12         | 3.635   |
| 200000             | false           | 10000                     | 12         | 3.430   |
| 200000             | false           | 20000                     | 12         | 3.289   |

After the change

| Number of entities | Also read data? | Indexed field disperssion | Iterations | Results |
|--------------------|-----------------|---------------------------|------------|---------|
| 100000             | true            | 5000                      | 12         | 351.896 |
| 100000             | true            | 10000                     | 12         | 239.120 |
| 100000             | true            | 20000                     | 12         | 187.573 |
| 100000             | false           | 5000                      | 12         | 133.697 |
| 100000             | false           | 10000                     | 12         | 131.780 |
| 100000             | false           | 20000                     | 12         | 124.380 |
| 200000             | true            | 5000                      | 12         | 626.666 |
| 200000             | true            | 10000                     | 12         | 339.028 |
| 200000             | true            | 20000                     | 12         | 241.808 |
| 200000             | false           | 5000                      | 12         | 133.883 |
| 200000             | false           | 10000                     | 12         | 143.313 |
| 200000             | false           | 20000                     | 12         | 124.538 |

I think, this approach in nitrite itself is counter productive. I think that app developer should separate app and db thread wherever required. 

So could you try this approach in your app and let me know that if you are facing issues or not?

According to the above logic, the test suite can be modified as below:

```java
public class NitriteCorruptedTest {
    private Nitrite db;
    private NitriteCollection collection;
    private String fileName = getRandomTempDbFile();
    private Thread thread;
    private ExecutorService dbPool = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());

    @Before
    public void setUp() {
        db = new NitriteBuilder()
                .filePath(fileName)
                .compressed()
                .openOrCreate();

        collection = db.getCollection("test");
        collection.remove(ALL);

        thread = new Thread(() -> {
            for (int i = 0; i < 50000; i++) {
				// this is vital to handle interruption in app thread
                if (Thread.interrupted()) {
                    break;
                }
                Document doc1 = createDocument(String.valueOf(System.currentTimeMillis()), "fn1")
                        .put("lastName", "ln1")
                        .put("data", new byte[]{1, 2, 3})
                        .put("body", "a quick brown fox jump over the lazy dog");
                System.out.println("Writing for iteration " + i);

				// execute the write inside a threadpool
                dbPool.submit(() -> collection.insert(doc1));
            }
        });
    }

    @After
    public void tearDown() throws IOException {
        if (!collection.isClosed()) {
            collection.remove(ALL);
            collection.close();
        }
        db.close();
        Files.delete(Paths.get(fileName));
    }

    @Test(timeout = 10000)
    public void testThread() throws InterruptedException {
        thread.start();
        Thread.sleep(100);
        thread.interrupt();
        Thread.sleep(1000);
        assertFalse(collection.isClosed());
        assertFalse(db.isClosed());
    }
}
```
