### ISSUE TITLE
Incorrect Deserialization Behaviour

### ISSUE THREAD

**Issue by a13u** [dizitart/nitrite-database#140]
I use Nitrite via Maven:
```
	<!--Nitrite -->
	<dependency>
 	   <groupId>org.dizitart</groupId>
 	   <artifactId>nitrite</artifactId>
  	  <version>3.0.0</version>
	</dependency>
```

I have the following code structure:
Class A
```
public class A {
    @Id
    public String name;

    public List<B> bs=new LinkedList<B>();
}

```

Class B

```
public class B {
    @Id
    public String bName;

    public List<B> preconditions=new LinkedList<B>(); 
}
```

My main class:
```
B b1=new B();
b1.bName="b1";

B b2=new B();
b2.bName="b2";

b1.preconditions.add(b2);

List<B> bs=new LinkedList<B>();
bs.add(b1);
bs.add(b2);

A a1=new A();
a1.name="mya1";
a1.bs=bs;

Nitrite db=Nitrite.builder()
	        .compressed()
	        .filePath("tmpDb.db").openOrCreate();
db.getRepository(A.class).insert(a1);

ObjectRepository<A> repo=db.getRepository(A.Class);

A myA=repo.find(ObjectFilters.eq("name","myA")).firstOrDefault();

System.out.println(myA.bs.get(0).preconditions.get(0));
System.out.println(myA.bs.get(0).preconditions.get(0).hashCode()+" --"  +myA.bs.get(0).preconditions.get(0).bName);
System.out.println(myA.bs.get(1));
System.out.println(myA.bs.get(1).hashCode() +" --" +  myA.bs.get(1).bName);
```

So before serializing I had a single B object (b2) which is referenced in both lists: a1.bs and b1.preconditions.
When I deserialize the object I get two B objects (one is referenced in a1.bs and a second which is referenced in b1.preconditions). So the B object in b1.preconditions does not reference to the B object in myA.bs. How can I prevent that two separate objects are created? I want to have the exect same Object structure in Java after deserialization...

**Comment by anidotnet** [comment]
You can't achieve this using serialization. Nitrite (which uses jackson behind the scene) does not keep track of references as per design (because nitrite does not do binary serialization). You can establish equality by overriding `equals()` and `hashCode()` in `B`, but reference equality can not be obtained this way.

But there is a way to achieve this. For this you have to skip auto serialization in nitrite and implement `Mappable` interface in your classes `A` and `B`. There you can keep a local cache of `B` instances and set the properties of your object according to your choice. Detailed documentation can be found here -https://www.dizitart.org/nitrite-database/#mappable

**N.B: I'll strongly suggest to upgrade your nitrite version to the latest.**
