### ISSUE TITLE
Unable to access JSON value's attribute using Filters eq method.

### ISSUE THREAD

**Issue by iamkiran** [dizitart/nitrite-database#181]
I am writing an API services which accepts the below JSON contents as input and I am successfully able to save the contents for the first time.
 
input : 
{
	"primarykey": "payloadId"
	,"payload":{
		"payloadId": "payload12",
		"payloadName": "payload name",
		"payloadStatus": "true"
	}

}

I am using this java code to verify the payloadId is already exist on not in the DB, but i am getting Document doc as null. please provide some assistance.

String primarykey = (String) feature.get("elementPrimayKey");
JSONObject payload = feature.getJSONObject("payload");
NitriteCollection nitritecollection = db.getCollection(collection);
Cursor cursor = nitritecollection.find(Filters.eq(primarykey, (String) payload.get(primarykey)));
Document doc = cursor.firstOrDefault();

**Comment by anidotnet** [comment]
The problem seems to be on this line

```
Cursor cursor = nitritecollection.find(Filters.eq(primarykey, (String) payload.get(primarykey)));
```

According to your sample json of payload

```json
"payload":{
"payloadId": "payload12",
"payloadName": "payload name",
"payloadStatus": "true"
}
```
it does not contains any field called `primarykey`. And I am not sure what `feature ` is and what it returns by `feature.get("elementPrimayKey");`.

It is more likely a problem with your own application logic rather than of nitrite. 

Why don't you use `ObjectRepository` instead of dealing manually with `JSONObject` which is very error prone?
