### ISSUE TITLE
Support for subset of data from the remote collection in the synchronization task

### ISSUE THREAD

**Issue by leacapello** [dizitart/nitrite-database#187]
It would be nice if could bring a subset of data from the remote collection in the synchronization task.

Something like:
```java
DataGateSyncTemplate syncTemplate = new DataGateSyncTemplate(dataGateClient, "remote-collection@userId");
syncTemplate.withRemoteFilter(eq("status", "done"));
```

**Comment by anidotnet** [comment]
What could be the possible use case of this feature that comes to your mind? 

Normally people are interested in syncing the whole collection between devices rather than only syncing some selective documents. What if the value of the field "status" changes? Should we stop syncing that document? Would not it lead to incoherent states between two devices?

**Comment by leacapello** [comment]
The idea is to make Nitrite DataGate multi-tenant, that way you avoid having to have multi-server and therefore multiple MongoDB for different clients that are grouped by data sets.

**Comment by anidotnet** [comment]
The trick for multi-tenancy is right there in the collection name - "remote-collection@userId". You can have same collection for n-number of users on a same datagate and mongodb server.

Moreover, creating tenants based on document criteria is a bad design, data isolation breaks easily when you change a field in the document.

**Comment by leacapello** [comment]
Ok, thanks!
