### ISSUE TITLE
Projection doesn't work if projected target type has field of abstract types

### ISSUE THREAD

**Issue by sheinbergon** [dizitart/nitrite-database#191]
Took me a while to find this bug.

It's related to the POADM library's inability to mock abstract class implementations without explicity factory specification

**Comment by anidotnet** [comment]
Projection does not work with abstract type or interface. Solid type must be provided for all fields. It is working as intended. I'll update the documentation to reflect this fact more clearly.

**Comment by sheinbergon** [comment]
So you're saying you can't project o a type if that type, or any of it's nested classes, contain an abstract field? that's a harsh restriction, don't you think?

**Comment by anidotnet** [comment]
It has nothing to do with podam. There has to be some concrete class for an abstract type used in the projection. Otherwise jackson would not know how to deserialize the values. May be you don't need to explicitly provide the concrete class as a data type in your projection class, but you need to provide `@JsonSubTypes` information for jackson to work.

Consider the below example:

```java
@Test
public void testIssue191() {
    ObjectRepository<B> repo = db.getRepository(B.class);
    B b = new B();
    C c = new C();
    c.setAddress("Kolkata");
    c.setName("Anindya");
    b.setC(c);
    b.setAge(1);
    b.setCountry("India");

    repo.insert(b);

    RecordIterable<D> project = repo.find().project(D.class);
    System.out.println(project.toList());
}

@Data
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY)
@JsonSubTypes({
    @JsonSubTypes.Type(value = C.class, name = "c")
})
abstract static class A {
    private String name;
}

@Data
@EqualsAndHashCode(callSuper = true)
static class C extends A {
    private String address;
}

@Data
static class B {
    @Id
    private Integer age;
    private C c;
    private String country;
}

@Data
@NoArgsConstructor
static class D {
    @Id
    private Integer age;
    private A c;
}
```

This perfectly works. I hope this answer your question.
