### ISSUE TITLE
More examples in the documentation

### ISSUE THREAD

**Issue by anidotnet** [dizitart/nitrite-database#27]
More simple examples would be helpful, according to this medium [response](https://medium.com/p/88f4fa7d936e/info)

**Comment by swissfreedev** [comment]
In my understanding there are two object types supported by nitrite:

1 The "untyped" document which can be a complex object with substructures and children collections.
These documents and can be as they are stored in the database, a unique objectid (nitriteid) 
is generated and can be used for further identification of the document instance

2. The type object which has a representation, for instance 

```
class employee
{
@Id
int empId;

string fullName;
}

```
when an instance of this object type is stored in the database, 
a unique objectid (nitrite) also generated
but for later updates the empId declared by the annotation @Id had to be set 
and has to be unique otherwise updates are not possible.

In my prototype I'm actually working on,
I have to deal with to categories of types object:
Those where I defines a unique Id when the object is created (Type A) 
and other where explicitly don't want to care about the id (Type B) 
and want the id to be generated by the database, 
similar to the autocountid in normal relational database:

Example

```
class region (Type A)
{
@Id
String regioncode;
String regionname;
...
}
```

regions ("BW", "Baden") ("H", "Hessen") OK


```
class Event (Type B)
{
//@Id

String eventtitle;
Date eventdate;
...
}

```
Event ("JSP workshop Berlin", "11.11.2018") ("Java advanced programming", "12.12.2018") 

Instances of the object "Event" can be inserted in the db but afterwards 
when I try to update them an exception occurs telling there are no @Id:

I could add an additional field annotated with 

```
@Id 
int eventID; 
```

but that makes the things more complicate:

Since the db already generates a unique nitriteID 
I would like use it as OID instead of having to generate a second identifier
that has to be made unique. I could use the nitrite document to stored object type but they are no type objects

Something like
```

public class Event {

    @Id
    NitriteId _id;
    
    String eventtitle;
    Date eventdate;
```

would be useful.

What are the best practices for these kind of objects?

**Comment by anidotnet** [comment]
Currently you cannot do this. Currently nitrite does not support complex objects in id field. While persisting,  ```NitriteId``` along with any other object will be converted as a map which is currently not supported in id field of object.

If you want to maintain an id, you can not use the auto-generated one in object, you have to specify it manually whose type is Number or String.

In future release I'll experiment on introducing NitriteId as id field in object. Created an issue for this - #50
