### ISSUE TITLE
when create Index dynamically, It'll not sync the generated DefaultObjectRepository instance

### ISSUE THREAD

**Issue by liuhaozzu** [dizitart/nitrite-database#39]
ObjectRepository repo = Nitrite.getRepository(clazz);
repo.createIndex(RESOURCE_ID, IndexOptions.indexOptions(IndexType.Unique));

repo.update(entity) then I get an Exception: throw new NotIdentifiableException(OBJ_REMOVE_FAILED_AS_NO_ID_FOUND);

//Hao Liu.

**Comment by anidotnet** [comment]
As far as I understand from the error message, you have not marked any field with ```@Id``` annotation in your entity class. Normally not every object needs ```@Id``` annotation but, if you do a operation like ```update(entity)``` or ```remove(entity)``` then you must add it. The id field will be used as a filter to identity the object from the repository. The other option is to use the overloaded method ```update(ObjectFilter filter, T update)``` where you need to provide a filter to identify the object.

Your code ```repo.createIndex(RESOURCE_ID, IndexOptions.indexOptions(IndexType.Unique));``` does not mark an id field as required by Nitrite, it just creates an index.

Moreover, your example code here is not complete, the error message you mentioned ```OBJ_REMOVE_FAILED_AS_NO_ID_FOUND``` would only come from a ```remove(entity)``` operation not from ```update(entity)``` operation. If adding ```@Id``` annotation does not solve your problem, then I suggest you to add a complete reproducible code along with the entity class here, so that I can reproduce your error.

**Comment by liuhaozzu** [comment]
I know that, however, the dynamically creating index of an entity is surported by the createIndex api, I think when users invoke this API, it should have the same effect of add an @Id annotation exeplicitly.

**Comment by anidotnet** [comment]
You can create as many index as you like, but those indices are not id. It is a special type of index which can only be created by using the ```@Id``` annotation. It's a design decision not to create id dynamically, otherwise it will create more problems than it will solve.

**Comment by liuhaozzu** [comment]
As I understand you create Index for id field if it's present in an entity by default. Then why don't you provide a default @Id filed?

**Comment by anidotnet** [comment]
I did not quite understand you, what do you mean by default id field? 

To clarify, internally, nitrite converts every object to a ```Document``` and store it in a ```MVMap```. Now ```Document``` has its own ```_id``` key which is an auto generated long field and can not be set by user and also can not be accessed by object. 

The field marked with ```@Id``` annotation is just a field used as a default filter to search an object, if that is not mentioned, user need to explicitly provide search filter. This design is to keep things simple.
