### ISSUE TITLE
Joining multiple ALL Filters

### ISSUE THREAD

**Issue by ptoews** [dizitart/nitrite-database#40]
Apparently this code 
```java
filter1 = Filters.ALL;
filter2 = Filters.ALL;
collection.find(Filters.and(filter1, filter2));
```
throws an invalid AND filter exception.
Wouldn't it be better if it was allowed, because in case multiple filters are used and each could be `null`/`Filters.ALL`, one has to check every single filter and combine the not-null ones with a lot of code.

**Comment by anidotnet** [comment]
There is a reason it was not allowed. ALL filter selects every elements in the collection. Now take these into consideration:

```java
filter1 = Filters.ALL;
filter2 = Filters.eq(...);

collection.find(Filters.and(filter1, filter2));
```
Here the result is basically same as 

```java
collection.find(filter2);
```

Again when you use these filters in OR operation

```java
filter1 = Filters.ALL;
filter2 = Filters.eq(...);

collection.find(Filters.or(filter1, filter2));
```

the result will be same as

```java
collection.find(filter1);
```
which is equal to all the elements in the collection. 

So if we allow null/ALL filter, it will negate the effect of other filters rendering the AND/OR operation useless. This will confuse most of the users, because it will be hard to find the cause, unless you restrict null filters in AND and OR operation.
