### ISSUE TITLE
Using alternate serializers

### ISSUE THREAD

**Issue by envas** [dizitart/nitrite-database#43]
Did you try to use an alternate JSON serializer to boost the DB speed? In my projects, I use (if possible) fastjson (https://github.com/alibaba/fastjson), which is a faster, lighter and has fewer dependencies than Jackson.

**Comment by anidotnet** [comment]
I chose jackson as default serializer as it has more flexibility. You can tweak the serialization with great extent (e.g. kotlin module, java time module etc. are few examples). 
Speed matters only if you want to read/write a huge chunk of data, otherwise jackson does not incur significant cost in terms of speed. I don't know how flexible fastjson or other libraries are, so jackson was my choice.

Though jackson was my personal choice, that does not mean you have to use it with nitrite even if you don't want to. You can implement your own ```NitriteMapper``` with your choice of serializer. Here is the doc: http://www.dizitart.org/nitrite-database/#nitritemapper

Even more, you can skip the whole serialization story and implement ```Mappable``` in your objects and can obtain lightning speed by avoiding reflection overhead. Doc: http://www.dizitart.org/nitrite-database/#mappable

**Comment by envas** [comment]
Thank you for your quick answer. I will try to write the fastjson mapper as described your docs. My problem is, that I am using Nitrite on embedded devices with limited RAM (for example on the RaspberryPi) and fastjson has significantly smaller footprint then Jackson (fewer dependencies).

**Comment by anidotnet** [comment]
Then I'll suggest you to use ```Mappable``` instead of any serializer, it will help you in speed and memory.

**Comment by anidotnet** [comment]
Closing this issue as original question was answered. For further query please feel free to raise another github issue or discuss in our gitter room.
