### ISSUE TITLE
ERROR NO2.8003 on Update object 

### ISSUE THREAD

**Issue by swissfreedev** [dizitart/nitrite-database#48]
Here is a code snippet using nitrite: first insert a region object,
then retrieve it from the database, in order to have an object with
autogenerated id, then i would like to update the object and store it again in the db.
With an non-autogenerated id it works fine, but not with a autogenerated.
I don't understand the error: //ERROR NO2.8003:
Since I retrieve the nitriteid from the db after having stored it in the db
my regSaved object should have an unique id and should be updateble
again. What wrong in this snippet ?

```java
Nitrite db = Nitrite.builder().compressed().filePath(dbname).openOrCreate();

ObjectRepository<Region> repRegion = db.getRepository(Region.class);

Cursor<Region> cursorRegion1 = repRegion.find();
for (Region r : cursorRegion1) {
     repRegion.remove(r);
}
Region reg = new Region();
reg.regionName="BadenX";

WriteResult writeResult = repRegion.insert(reg); // insert a new region
NitriteId nitriteId = Iterables.firstOrDefault(writeResult); //gets the id of the new region after insert

Region regSaved = repRegion.getById(nitriteId); // retrieve the object
reg.regionName="Baden"; //update the name
repRegion.update(reg); //ERROR NO2.8003: update operation failed as no id value found for the object 
```

**Comment by anidotnet** [comment]
Every update/remove operation needs a filter to identify an object uniquely from the repository. In an ```ObjectRepository```, ```NitriteId``` is not the intended id you are looking for. As ```NitriteId``` only contains long value, it is not suitable for user defined id of an object. Its a limitation of ```ObjectRepository``` that you can not update/remove an object using auto-generated ```NitriteId```. Your object needs to have a field marked with ```@Id```. 
The reason is, once you have an object there is no way you can associate it with a ```NitriteId```, because an arbitrary object does not hold that information.

But ```NitriteCollection``` does not suffer from this limitation. The ```NitriteId``` value is stored in **_id** field of a ```Document```. So there you can do the intended update/remove using the auto-generated id.

I hope this clarifies your confusion.

**Comment by swissfreedev** [comment]
Thanks very fine, it works, here an example:

The Entity:
@Data
public class Region {
   
    @Id
    public String regionCode;    
    
    public String regionName;
  
    public List<Gipfel> gipfelList;
         ....

the Unittest:

Test()
{
        Region reg = new Region();
        reg.regionCode="WA";
        reg.regionName="Wallis";         
        Region regSaved = WriteToDB(reg); //save the object and retrieve it again for further use
                    
        Gipfel gipfel = new Gipfel("Matterhorn", 4478, reg);         
        regSaved.gipfelList.add(gipfel); 
        repRegion.update(regSaved);
        repGipfel.insert(gipfel);
        gipfel = new Gipfel("Monte Rosa", 4600, reg);          
        regSaved.gipfelList.add(gipfel); 
        repRegion.update(regSaved);
        repGipfel.insert(gipfel);

    }
   
    Region WriteToDB (Region reg)
    {
        WriteResult writeResult = repRegion.insert(reg);  
        NitriteId nitriteId = Iterables.firstOrDefault(writeResult);          
        return repRegion.getById(nitriteId);
    }
