### ISSUE TITLE
Is this db works fine with Kotlin and data classes?

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#49]
Hello! Thanks for this project, it looks promising!

I'd like to use this library in production, is it reliable?
Can I use it with Kotlin's data classes?
Will it work properly for Android and iOS development with Intel MOE?

**Comment by anidotnet** [comment]
Never tried with Intel MOE so can't tell, but as far as I know nitrite is already being used in some of the apps in android market. As you mentioned kotlin, I'll suggest you to use potassium-nitrite instead of nitrite directly. It has support for kotlin data classes. 

If you face any issue, I am always here to help you out. And if you are successful with your project with nitrite, please don't forget to spread the word :smiley:

**Comment by Try4W** [comment]
Thanks for quick reply! I will try it.

PS
Kotlin-support a little bit hidden from eyes :)
It will be great if potassium-nitrite will be described in README.MD and docs.

**Comment by anidotnet** [comment]
You are absolutely right. I'll make the changes in next iteration.

**Comment by anidotnet** [comment]
README updated.
