### ISSUE TITLE
Is there a way to extend to the POJOs with additional fields while using an existing DB?

### ISSUE THREAD

**Issue by staeff777** [dizitart/nitrite-database#66]
I created a class `Person` with the fields `name`  and  `age` and stored some instances of it in an `ObjectRepository`. 

At some point in the lifecycle of my app I may want to add a `hobbies` field to `Person`. However, this will result in following error:
```
Caused by: java.io.InvalidClassException: de.itd.nitrite.test.Person; local class incompatible: stream classdesc serialVersionUID = -50986882814728565, ...
```
With Json deserialization alone, this should be no problem as long as I provide a default value for `hobby`.

Is there a recommendation how to enable backward compatibility and handle class extends? 

Update: Ok.. I can solve it by implementing Serializable and using the same serialVersionUID.

**Comment by anidotnet** [comment]
Yes you are right. As long as you provide a `serialVersionUID` you should be good to go. 

Another way is to implement `Mappable` interface in your class. Not only it will solve this problem, it is blazing fast also as it does not have reflection overhead.

Just curious what version of nitrite are you using?

**Comment by staeff777** [comment]
Thank you for the hint. I must have overread it in your very good documentation.

I'm using verion 3.0.0.

**Comment by anidotnet** [comment]
I am closing this issue as resolved. If you have further concerns regarding it please feel free to comment here or join our gitter room.

**Comment by ArthurSav** [comment]
> Another way is to implement Mappable interface in your class. Not only it will solve this problem, it is blazing fast also as it does not have reflection overhead.

Tried using only Mappable without Serializable and nitrite could not deserialize the object. 

Using nitrite.getRepository to retrieve the object

> Caused by: java.lang.IllegalArgumentException: Could not deserialize

Once i implement Serializable it works again but i'd like to avoid setting serialVersionUID to every POJO.

Any special requirements for saving/retrieving Mappables? Using a nested object that all implement Mappable

**Comment by anidotnet** [comment]
@ArthurSav please look into this [test](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/mapper/MapperTest.java#L67) where nitrite is persisting an object which implements `Mappable` and **does not** implement `Serializable`. Look into this [example class](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/mapper/MappableEmployee.java) also for implementation, it contains a nested object also.

> Once i implement Serializable it works again but i'd like to avoid setting serialVersionUID to every POJO.

Based on your comment, I guess you are using nested object which are not properly handled in read/write methods. May be you are directly putting those object in the parent document and that's why it asks for `serialVersionUID`. The example class mentioned above will help you understand how to handle nested object properly.

> Any special requirements for saving/retrieving Mappables? Does it handle lists? Using a nested object that all implement Mappable

The `Mappable` interface is for ultimate flexibility. It totally depends upon you how you want to create a document from an object and vise versa. Nitrite will not override anything here in this conversion. You can even convert your whole object into some custom encoded string and store it in the document and read it from there and decode it to manually create the object back.

I hope it clears things up a bit for you. If you still are in doubt feel free to ask me.

**Comment by ArthurSav** [comment]
Thanks for the clarification.
I was indeed inserting/retrieving the nested objects directly which seems to be the issue.
