### ISSUE TITLE
Add MVStore Encryption to NitriteStore through NitriteBuilder.

### ISSUE THREAD

**Issue by objectorange** [dizitart/nitrite-database#70]
One of H2's great features is Encrypted files. This is provided in MVStore but isn't exposed by the NitriteBuilder.

**Comment by anidotnet** [comment]
Well I left it for a reason. MVStore does not encrypt MVMap entities, it encrypts the whole database file. So for every read/write operation, nitrite has to decrypt the whole database file and store it in memory everytime, which is a huge performance hit when the file size gets big and which I can't afford.

If you want to store data encrypted, you can implement `Mappable` in your pojo and encrypt/decrypt data in the `Document` level instead of encrypting the whole database file. It will  be way more convenient and performant.

**Comment by objectorange** [comment]
Ok, that makes sense. Thanks.

Sincerely,
Brian Taylor

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
